add_hist – pyplot-fortran
add_hist Subroutine
Jimmy Leta
37 statements
Source File
private subroutine add_hist(me, x, label, xlim, ylim, xscale, yscale, bins, normed, cumulative)
Add a histogram plot.
Arguments
Type Intent Optional Attributes Name
class(pyplot), intent(inout) :: me
pyplot handler
real(kind=wp), intent(in), dimension(:) :: x
array of data
character(len=*), intent(in) :: label
plot label
real(kind=wp), intent(in), optional dimension(2) :: xlim
x-axis range
real(kind=wp), intent(in), optional dimension(2) :: ylim
y-axis range
character(len=*), intent(in), optional :: xscale
example: 'linear' (default), 'log'
character(len=*), intent(in), optional :: yscale
example: 'linear' (default), 'log'
integer, intent(in), optional :: bins
number of bins
logical, intent(in), optional :: normed
boolean flag that determines whether bin counts are normalized
logical, intent(in), optional :: cumulative
boolean flag that determines whether histogram represents the cumulative density of dataset
Calls
Source Code
add_hist
Source Code
    subroutine add_hist(me, x, label, xlim, ylim, xscale, yscale, bins, normed, cumulative)
    class(pyplot),          intent (inout)        :: me           !! pyplot handler
    real(wp), dimension(:), intent (in)           :: x            !! array of data
    character(len=*),       intent (in)           :: label        !! plot label
    real(wp),dimension(2),  intent (in), optional :: xlim         !! x-axis range
    real(wp),dimension(2),  intent (in), optional :: ylim         !! y-axis range
    character(len=*),       intent (in), optional :: xscale       !! example: 'linear' (default), 'log'
    character(len=*),       intent (in), optional :: yscale       !! example: 'linear' (default), 'log'
    integer,                intent (in), optional :: bins         !! number of bins
    logical,                intent (in), optional :: normed       !! boolean flag that determines whether bin counts are normalized
    logical,                intent (in), optional :: cumulative   !! boolean flag that determines whether histogram represents the cumulative density of dataset
    character(len=*), parameter   :: xname = 'x'      !! x variable name for script
    character(len=:), allocatable :: xstr             !! x values stringified
    character(len=:), allocatable :: xlimstr          !! xlim values stringified
    character(len=:), allocatable :: ylimstr          !! ylim values stringified
    character(len=:), allocatable :: normedstr        !! optional stuff
    character(len=:), allocatable :: cumulativestr    !!
    character(len=max_int_len)    :: binsstr          !!
    if (allocated(me%str)) then
        !axis limits (optional):
        if (present(xlim)) call vec_to_string(xlim, me%real_fmt, xlimstr, me%use_numpy)
        if (present(ylim)) call vec_to_string(ylim, me%real_fmt, ylimstr, me%use_numpy)
        !convert the arrays to strings:
        call vec_to_string(x, me%real_fmt, xstr, me%use_numpy)
        !write the arrays:
        call me%add_str(trim(xname)//' = '//xstr)
        call me%add_str('')
        !get optional inputs (if not present, set default value):
        call optional_int_to_string(bins, binsstr, '10')
        call optional_logical_to_string(normed, normedstr, 'False')
        call optional_logical_to_string(cumulative, cumulativestr, 'False')
        !write the plot statement:
        call me%add_str('ax.hist('//&
                        trim(xname)//','//&
                        'label="'//trim(label)//'",'//&
                        'bins='//trim(binsstr)//','//&
                        'cumulative='//trim(cumulativestr)//','//&
                        'normed='//trim(normedstr)//')')
        !axis limits:
        if (allocated(xlimstr)) call me%add_str('ax.set_xlim('//xlimstr//')')
        if (allocated(ylimstr)) call me%add_str('ax.set_ylim('//ylimstr//')')
        !axis scales:
        if (present(xscale)) call me%add_str('ax.set_xscale("'//xscale//'")')
        if (present(yscale)) call me%add_str('ax.set_yscale("'//yscale//'")')
        call me%add_str('')
    else
        error stop 'Error in add_plot: pyplot class not properly initialized.'
    end if
    end subroutine add_hist
All Procedures
add_3d_plot add_bar add_contour add_hist add_imshow add_plot add_str destroy execute initialize integer_to_string matrix_to_string optional_int_to_string optional_logical_to_string savefig vec_to_string
Call graph
add_hist calls optional_logical_to_string, vec_to_string, optional_int_to_string
optional_int_to_string calls integer_to_string