integer_to_string – pyplot-fortran
integer_to_string Subroutine
Jacob Williams
12 statements
Source File
private subroutine integer_to_string(i, s)
Integer to string conversion.
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: i
integer value
character(len=*), intent(out) :: s
integer value stringified
Called By
Source Code
integer_to_string
Source Code
    subroutine integer_to_string(i, s)
    integer,          intent(in), optional  :: i     !! integer value
    character(len=*), intent(out)           :: s     !! integer value stringified
    integer                                 :: istat !! IO status
    write(s, int_fmt, iostat=istat) i
    if (istat/=0) then
        write(error_unit,'(A)') 'Error converting integer to string'
        s = '****'
    else
        s = adjustl(s)
    end if
    end subroutine integer_to_string
All Procedures
add_3d_plot add_bar add_contour add_hist add_imshow add_plot add_sphere add_str destroy execute finish_ops initialize integer_to_string matrix_to_string optional_int_to_string optional_logical_to_string real_to_string savefig showfig vec_to_string
Call graph
optional_int_to_string calls integer_to_string
initialize calls integer_to_string, optional_int_to_string
add_hist calls optional_int_to_string
add_sphere calls optional_int_to_string
add_contour calls optional_int_to_string
add_plot calls optional_int_to_string
add_3d_plot calls optional_int_to_string