optional_logical_to_string – pyplot-fortran
optional_logical_to_string Subroutine
Jacob Williams
14 statements
Source File
private subroutine optional_logical_to_string(logical_value, string_value, default_value)
Logical to string, specifying the default value if the optional argument is not present.
Arguments
Type Intent Optional Attributes Name
logical, intent(in), optional :: logical_value
character(len=:), intent(out), allocatable :: string_value
integer value stringified
character(len=*), intent(in) :: default_value
default integer value
Called by
Source Code
    subroutine optional_logical_to_string(logical_value, string_value, default_value)
    logical,intent(in),optional              :: logical_value
    character(len=:),allocatable,intent(out) :: string_value   !! integer value stringified
    character(len=*),intent(in)              :: default_value  !! default integer value
    if (present(logical_value)) then
        if (logical_value) then
            string_value = 'True'
        else
            string_value = 'False'
        end if
    else
        string_value = default_value
    end if
    end subroutine optional_logical_to_string
Call graph
add_hist calls optional_logical_to_string
add_sphere calls optional_logical_to_string
plot_surface calls optional_logical_to_string
plot_wireframe calls optional_logical_to_string