optional_int_to_string – pyplot-fortran
optional_int_to_string Subroutine
Jacob Williams
10 statements
Source File
private subroutine optional_int_to_string(int_value, string_value, default_value)
Integer to string, specifying the default value if the optional argument is not present.
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: int_value
integer value
character(len=*), intent(out) :: string_value
integer value stringified
character(len=*), intent(in) :: default_value
default integer value
Calls
Called By
Source Code
optional_int_to_string
Source Code
    subroutine optional_int_to_string(int_value, string_value, default_value)
    integer,          intent(in), optional :: int_value      !! integer value
    character(len=*), intent(out)          :: string_value   !! integer value stringified
    character(len=*), intent(in)           :: default_value  !! default integer value
    if (present(int_value)) then
        call integer_to_string(int_value, string_value)
    else
        string_value = default_value
    end if
    end subroutine optional_int_to_string
All Procedures
add_3d_plot add_bar add_contour add_hist add_imshow add_plot add_sphere add_str destroy execute finish_ops initialize integer_to_string matrix_to_string optional_int_to_string optional_logical_to_string real_to_string savefig showfig vec_to_string
Call graph
optional_int_to_string calls integer_to_string
initialize calls optional_int_to_string
add_contour calls optional_int_to_string
add_plot calls optional_int_to_string
add_sphere calls optional_int_to_string
add_3d_plot calls optional_int_to_string
add_hist calls optional_int_to_string