showfig – pyplot-fortran
showfig Subroutine
Johannes Rieke
6/16/2017
18 statements
Source File
private subroutine showfig(me, pyfile, istat, python)
Shows the figure.
Type Bound
pyplot
Arguments
Type Intent Optional Attributes Name
class(pyplot), intent(inout) :: me
pyplot handler
character(len=*), intent(in), optional :: pyfile
name of the Python script to generate
integer, intent(out), optional :: istat
status output (0 means no problems)
character(len=*), intent(in), optional :: python
python executable to use. (by default, this is 'python')
Calls
Source Code
    subroutine showfig(me, pyfile, istat, python)
    class(pyplot),    intent(inout)          :: me      !! pyplot handler
    character(len=*), intent(in), optional   :: pyfile  !! name of the Python script to generate
    integer,          intent (out), optional :: istat   !! status output (0 means no problems)
    character(len=*), intent(in),optional    :: python  !! python executable to use. (by default, this is 'python')
    if (.not. allocated(me%str)) then
        if (present(istat)) istat = -1
        write(error_unit,'(A)') 'error in showfig: pyplot class not properly initialized.'
    else if (me%use_oo_api) then
        if (present(istat)) istat = -2
        write(error_unit,'(A)') 'error in showfig: not compatible with "use_oo_api" option'
    else
        if (present(istat)) istat = 0
        !finish up the string:
        call me%finish_ops()
        !show figure:
        call me%add_str('plt.show()')
        !run it:
        call me%execute(pyfile, istat=istat, python=python)
    end if
    end subroutine showfig
Call graph
showfig calls add_str, execute, finish_ops
finish_ops calls add_str